server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userFallBack
        - id: todo-service
          uri: lb://TODO-SERVICE
          predicates:
            - Path=/todo-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: todo-service
                fallbackuri: forward:/todoFallback

jwt:
  secret: my-secret-key

# DataSource Configs
# Actually we need to loot at user-service db but this is just sample via H2 db
# and I just wanna to show how to use security on gateway with JWT
  datasource:
    url: jdbc:h2:mem:user-db-db;DB_CLOSE_DELAY=-1;
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
