server:
  port: 9090

spring:
  application:
    name: gateway-service

zuul:
  ignoredServices: '*'
  routes:
    user-service:
      path: /user-service/**
      serviceId: user-service
    todo-service:
      path: /todo-service/**
      serviceId: todo-service

jwt:
  secret: my-secret-key

  # DataSource Configs
  # Actually we need to loot at user-service db but this is just sample via H2 db
  # and I just wanna to show how to use security on gateway with JWT
  datasource:
    url: jdbc:h2:mem:user-db-db;DB_CLOSE_DELAY=-1;
    data-username: sa
    data-password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
